// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facility_grounding: {
        name: "facility_grounding";
        parameters: {
          /** STRING - use sql.string() */
          query: SQLStringMarker;
          /** INT - use sql.int() */
          resultLimit: SQLNumberMarker;
        };
        result: Array<{
          /** Stable internal golden facility ID (using unique_id) */
          facility_id: string;
          /** Cleaned and standardized facility name */
          canonical_name: string;
          /** Normalized facility type: hospital, clinic, dentist, pharmacy, etc. */
          facility_type: string;
          /** Public, private, charitable, trust, government, corporate, NGO, academic, etc. */
          operator_type: string;
          /** City or locality */
          city: string;
          /** State, province, or region */
          state_region: string;
          /** Postal or ZIP code */
          postal_code: string;
          /** Best full address string */
          address_full: string;
          /** @sqlType STRING */
          contacts: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          procedures: string;
          /** Overall confidence in the golden identity record (0-1) */
          gold_confidence_score: number;
          /** @sqlType DOUBLE */
          specialty_confidence: number;
          /** @sqlType DOUBLE */
          procedure_confidence: number;
          /** @sqlType BIGINT */
          specialty_evidence_count: number;
          /** @sqlType INT */
          has_center_of_excellence: number;
          /** @sqlType INT */
          has_inpatient_support: number;
          /** @sqlType INT */
          has_outpatient_support: number;
          /** @sqlType INT */
          requires_special_equipment: number;
          /** @sqlType DOUBLE */
          match_score: number;
        }>;
      };
  }
}
