// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    referral_search: {
        name: "referral_search";
        parameters: {
          /** STRING - use sql.string() */
          careNeed: SQLStringMarker;
          /** STRING - use sql.string() */
          location: SQLStringMarker;
          /** INT - use sql.int() */
          confidenceWeight: SQLNumberMarker;
          /** INT - use sql.int() */
          accessWeight: SQLNumberMarker;
          /** INT - use sql.int() */
          needWeight: SQLNumberMarker;
          /** INT - use sql.int() */
          limit: SQLNumberMarker;
        };
        result: Array<{
          /** Foreign key to gold_facility.facility_id */
          facility_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType STRING */
          operator_type: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state_name: string;
          /** @sqlType STRING */
          postal_code: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          official_phone: string;
          /** @sqlType STRING */
          official_website: string;
          /** @sqlType DOUBLE */
          evidence_score: number;
          /** @sqlType STRING */
          evidence_confidence: string;
          /** @sqlType STRING */
          record_quality: string;
          /** @sqlType DECIMAL(16,1) */
          capability_match_score: number;
          /** @sqlType INT */
          location_match_score: number;
          /** @sqlType DOUBLE */
          referral_score: number;
          /** @sqlType DOUBLE */
          district_need_score: number;
          /** @sqlType BOOLEAN */
          district_context_available: boolean;
          /** @sqlType STRING */
          evidence_description: string;
          /** @sqlType STRING */
          evidence_specialties: string;
          /** @sqlType STRING */
          evidence_procedures: string;
          /** @sqlType STRING */
          evidence_equipment: string;
          /** @sqlType STRING */
          evidence_capabilities: string;
          /** @sqlType STRING */
          evidence_source_urls: string;
          /** @sqlType TIMESTAMP */
          page_update_date: string;
        }>;
      };
    referral_summary: {
        name: "referral_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          facility_count: number;
          /** @sqlType BIGINT */
          high_confidence_count: number;
          /** @sqlType BIGINT */
          contactable_count: number;
          /** @sqlType INT */
          district_context_count: number;
          /** @sqlType DOUBLE */
          average_evidence_score: number;
        }>;
      };
  }
}
